# Generated by Django 3.1.4 on 2021-01-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_auto_20210113_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='free_seats',
            field=models.IntegerField(null=True, verbose_name='صندلی های خالی'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='saleable_seats',
            field=models.IntegerField(null=True, verbose_name='صندلی های قابل فروش'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(verbose_name='زمان شروع نمایش'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال فروش بلیت'), (3, 'بلیت ها تمام شد'), (4, 'فروش بلیت بسته شد'), (5, 'فیلم پخش شد'), (6, 'سانس لغو شد')], verbose_name='وضعیت'),
        ),
    ]
